### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by birnbuazn** [comit-network/RFCs#114]
### RFC - 003

- [x] In RFC - 003 I would state explicitly, that the alpha-redeem identity for a SWAP response is the same identity as the alpha-refund identity in the SWAP request, because this is not mentioned clearly.

- [x] In the sequence diagram in the appendix of RFC - 003 it looks like the opt block for erc20 does not differ from the normal flow. Why include that here in the diagram then as optional?

### RFC - 004 and RFC - 006

- [x] When talking about the "Quantity" property: I would get rid of the comment about the JSON encoding. It should be clear anyway, that JSON representations are not typed and every value is encoded using double quotes. Mentioning it here just creates confusion. (I was looking for some magical representational mapping instead :) )

### RFC - 005

- [x] Your link to RFC - 005 on the main page seems to be broken :D

### RFC - 006

- [x] Small thing again, but I would restructure the paragraph about network parameters: General considerations and constraints first, then list possible values in subsequent paragraphs.

**Comment by thomaseizinger** [comment]
Hey @birnbuazn ,

thank you very much for that feedback. I'll comment on this issue as part of resolving the individual items :)

> When talking about the "Quantity" property: I would get rid of the comment about the JSON encoding. It should be clear anyway, that JSON representations are not typed and every value is encoded using double quotes. Mentioning it here just creates confusion. (I was looking for some magical representational mapping instead :) )

Taken care of in https://github.com/comit-network/RFCs/pull/92.

**Comment by thomaseizinger** [comment]
>  Your link to RFC - 005 on the main page seems to be broken :D

Also taken care of in #92.

**Comment by thomaseizinger** [comment]
@birnbuazn 

> In RFC - 003 I would state explicitly, that the alpha-redeem identity for a SWAP response is the same identity as the alpha-refund identity in the SWAP request, because this is not mentioned clearly.

Do you mean with "same" as in same data type? Because it is _not_ necessarily the same value. They are both referred to as `α::Identity` which should be read as "alpha identity". Since "alpha" refers to a ledger, the datatype of the identities are the same (check the registry for which ones they are for a particular ledger)

The whole greek-letter notation is quite confusing though but that will be changed with: https://github.com/comit-network/RFCs/issues/68

**Comment by thomaseizinger** [comment]
@birnbuazn 

> In the sequence diagram in the appendix of RFC - 003 it looks like the opt block for erc20 does not differ from the normal flow. Why include that here in the diagram then as optional?

The difference is that for a token asset like ERC20, the _deployment_ of the HTLC does not include money. It just deploys an empty HTLCs. The funding step is separate because the funding happens by transferring tokens on a different contract (the ERC20) contract.
We are not very happy about this but there is little we can do about it. Unfortunately, we cannot deploy a contract and transfer ERC20 to it at the same time :/

**Comment by thomaseizinger** [comment]
@birnbuazn 

>   Small thing again, but I would restructure the paragraph about network parameters: General considerations and constraints first, then list possible values in subsequent paragraphs.

Thanks for the feedback!
That section is likely going to change in the hopefully near future (https://github.com/comit-network/RFCs/issues/73). Since it is still quite short and fairly easy to understand, I'll leave it like that :)
