### ISSUE TITLE
Clarify use of headers vs body

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/RFCs#99]
It is not clear from just reading RFC001, how headers and body should be used.

Reason is: Message should be able to be parsed in a single pass, that requires headers to be able to be parsed orthogonally (i.e. they don't depend on each other).
Contrary, field names and datatypes in body may depend on the value of headers.

**Comment by birnbuazn** [comment]
While reading RFC004 I again got the impression, that it's rather arbitrary, which information goes into headers and what goes into the body. IMHO this rather confuses instead of helps.

I would not let implementation details (such as single pass parsing) come into my way, when specifying the protocol

**Comment by thomaseizinger** [comment]
https://github.com/comit-network/RFCs/issues/121 is kind of accepted. With it, the concept of headers and body is removed.
